title: Sara Fernandes
# logo: assets/sadcat.jpg
description: Welcome to my portfolio. I\''m a first year BSc Data Science student at BPP, with experience as a Data Analyst in the financial industry.
# show_downloads: true
theme: jekyll-theme-minimal
